/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_jim_javadll_test */

#ifndef _Included_com_jim_javadll_test
#define _Included_com_jim_javadll_test
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_jim_javadll_test
 * Method:    ini
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_jim_javadll_test_ini
  (JNIEnv *, jclass);

/*
 * Class:     com_jim_javadll_test
 * Method:    PLR
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_jim_javadll_test_PLR
  (JNIEnv *, jclass, jstring);

/*
 * Class:     com_jim_javadll_test
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_jim_javadll_test_add
  (JNIEnv *, jclass, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
